variables:
  RELEASE_IMAGE_VERSION: "latest"
  RELEASE_IMAGE: "nanawel/placeholder-service"
  PUBLIC_IMAGE: "nanawel/placeholder-service"

stages:
  - check
  - build
  - release

before_script:
  - time docker info
  - '[ -z "${REGISTRY_SERVER}" ] || time docker login ${REGISTRY_SERVER}'
  - env

build_image:
  stage: build
  script:
    - time docker build -t ${RELEASE_IMAGE}:${RELEASE_IMAGE_VERSION} -f docker/standalone/Dockerfile .
    - time docker tag reciphpes:${RELEASE_IMAGE_VERSION} ${RELEASE_IMAGE}:${CI_COMMIT_SHORT_SHA}
    - time docker push ${RELEASE_IMAGE}:${CI_COMMIT_SHORT_SHA}
  tags:
    - shell
    - docker

push_image_latest:
  stage: release
  script:
    - time docker pull ${RELEASE_IMAGE}:${CI_COMMIT_SHORT_SHA}
    - time docker tag ${RELEASE_IMAGE}:${CI_COMMIT_SHORT_SHA} ${RELEASE_IMAGE}:latest
    - time docker push ${RELEASE_IMAGE}:latest
  tags:
    - shell
    - docker
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "master"'

push_image_tagged:
  stage: release
  script:
    - time docker pull ${RELEASE_IMAGE}:${CI_COMMIT_SHORT_SHA}
    - time docker tag ${RELEASE_IMAGE}:${CI_COMMIT_SHORT_SHA} ${RELEASE_IMAGE}:${CI_COMMIT_TAG}
    - time docker push ${RELEASE_IMAGE}:${CI_COMMIT_TAG}
  tags:
    - shell
    - docker
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'

push_image_public:
  stage: release
  script:
    - docker login -u "${PUBLIC_REGISTRY_USERNAME}" -p "${PUBLIC_REGISTRY_TOKEN}"
    - time docker pull ${RELEASE_IMAGE}:${CI_COMMIT_SHORT_SHA}
    - time docker tag ${RELEASE_IMAGE}:${CI_COMMIT_SHORT_SHA} ${PUBLIC_IMAGE}:latest
    - time docker push ${PUBLIC_IMAGE}:latest
    - '[ -z "${CI_COMMIT_TAG}" ] || time docker tag ${RELEASE_IMAGE}:${CI_COMMIT_SHORT_SHA} ${PUBLIC_IMAGE}:${CI_COMMIT_TAG}'
    - '[ -z "${CI_COMMIT_TAG}" ] || time docker push ${PUBLIC_IMAGE}:${CI_COMMIT_TAG}'
  tags:
    - shell
    - docker
  rules:
    - when: manual
      if: '$RELEASE_IMAGE != $PUBLIC_IMAGE'
